apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  labels:
    app: demonew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demonew
  template:
    metadata:
      labels:
        app: demonew
    spec:
      containers:
        - name: demonew
          image: sriharipriya/demonew:${{ github.run_number }}

          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demonew-loadbalancer-service
  labels:
    app: demonew
spec:
  type: LoadBalancer
  selector:
    app: demonew
  ports:
    - port: 8080
      targetPort: 8080
